/**
 * EMPL — loi ordinaire (cycle-projet-acte).
 * Même squelette que le petit crédit ; objectType loi + accent délai référendaire.
 */
export const EMPL_LOI = {
  id: "empl-loi",
  title: "EMPL — loi ordinaire",
  subtitle: "Projet de loi · délai référendaire Cst-VD art. 84",
  objectId: "obj-empl-loi",
  objectType: "loi",
  objectLabel: "EMPL — exposé des motifs et projet de loi",
  pilotBodyId: "dep-dfa",
  lifecycleId: "cycle-projet-acte",
  steps: [
    {
      id: "loi-1-ce",
      from: "en-elaboration",
      to: "adopte-ce",
      by: "decision",
      decisionType: "adopte",
      weekdayTag: "ce",
      siteId: "chateau",
      actorLabel: "DPT → Collège du CE",
      actLabel: "Adopter l'EMPL au collège",
      lessonWrongDay: "Le collège du CE siège le mercredi.",
      successLesson:
        "Le collège adopte l'EMPL (projet de loi). ★ Distinct d'un EMPD (décret).",
    },
    {
      id: "loi-2-saisine",
      from: "adopte-ce",
      to: "saisine-commission",
      by: "handover",
      siteId: "parlement",
      fromSiteId: "chateau",
      actorLabel: "Chancellerie → SGC",
      actLabel: "Transmettre au Grand Conseil",
      successLesson: "Navette : le projet de loi saisit le GC.",
    },
    {
      id: "loi-3-commission",
      from: "saisine-commission",
      to: "rapports-deposes",
      by: "handover",
      siteId: "parlement",
      actorLabel: "Commission",
      actLabel: "Déposer le rapport",
      successLesson: "Rapport de commission déposé avant le plénum.",
    },
    {
      id: "loi-4-eem",
      from: "rapports-deposes",
      to: "entree-en-matiere",
      by: "decision",
      decisionType: "adopte",
      weekdayTag: "gc",
      siteId: "parlement",
      actorLabel: "Plénum",
      actLabel: "Entrée en matière",
      lessonWrongDay: "Le Grand Conseil siège le mardi.",
      successLesson: "Entrée en matière acceptée (art. 94 LGC).",
    },
    {
      id: "loi-5-debats",
      from: "entree-en-matiere",
      to: "en-debats",
      by: "decision",
      decisionType: "adopte",
      weekdayTag: "gc",
      siteId: "parlement",
      actorLabel: "Plénum",
      actLabel: "Débats (lectures)",
      successLesson: "Débats en plénum (art. 100–101).",
    },
    {
      id: "loi-6-vote",
      from: "en-debats",
      to: "mise-au-point",
      by: "decision",
      decisionType: "adopte",
      weekdayTag: "gc",
      siteId: "parlement",
      actorLabel: "Plénum — scrutin",
      actLabel: "Vote final de la loi",
      successLesson: "Loi adoptée. Mise au point du texte.",
    },
    {
      id: "loi-7-pub",
      from: "mise-au-point",
      to: "publie-delai-referendaire",
      by: "handover",
      siteId: "chateau",
      fromSiteId: "parlement",
      actorLabel: "Chancellerie — FAO",
      actLabel: "Publier (délai référendaire)",
      successLesson:
        "★ Publication FAO (Feuille des avis officiels) : délai référendaire facultatif (Cst-VD art. 84). Si aboutissement → parcours type S17 (peuple hors carte).",
      startDeadline: "delai-referendaire",
    },
    {
      id: "loi-8-promulgue",
      from: "publie-delai-referendaire",
      to: "promulgue",
      by: "handover",
      siteId: "chateau",
      actorLabel: "Chancellerie",
      actLabel: "Promulguer la loi",
      successLesson: "Loi promulguée après échéance du délai (ou sans référendum).",
    },
  ],
};
